# MedSAM2 Inference Configuration - evaluation RUN
# Experiment: Nam_exp_01082026

model:
  config_path: ./external/MedSAM2/sam2/configs/sam2.1_hiera_large1024_VTS_opt.yaml
  checkpoint_path: ./external/MedSAM2/exp_log/MedSAM2_VTS_large/checkpoints/checkpoint.pt
  device: cuda

paths:
  input_folder: ./data_yolo_ribbon_2_px/images/test
  output_folder: ./inference_output_medsam2_Nam_exp_01232026_all1
  ground_truth_folder: ./data_yolo_ribbon_2_px/labels/test

data:
  process_all: true
  specific_images:

inference:
  mask_threshold: 0.0
  multimask_output: false

evaluation:
  enabled: true
  metrics:
    - p2cp_mean
    - p2cp_rms
    - jaccard_index
  closed_articulators:
    - thyroid-cartilage
    - vocal-folds
  save_csv: true
  save_visualizations: true
  save_per_image: true
  save_summary: false

labels:
  0: arytenoid-cartilage
  1: epiglottis
  2: lower-lip
  3: pharynx
  4: soft-palate-midline
  5: thyroid-cartilage
  6: tongue
  7: upper-lip
  8: vocal-folds

postprocessing:
  use_vt_tracker: true

visualization:
  dpi: 100
  figsize: [20, 14]
  show_confidence: true
  overlay_alpha: 0.5
  contour_linewidth: 2.5
  gt_linestyle: '-'
  pred_linestyle: '--'
  show_raw_segmentation: true
